# fly.toml app configuration file generated for supabase-studio-bec on 2025-07-22T14:49:20+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supabase-studio-bec'
primary_region = 'lhr'

[build]
  image = 'public.ecr.aws/supabase/studio:2025.07.07-sha-1d3b0ba'

[env]
  NEXT_ANALYTICS_BACKEND_PROVIDER = 'postgres'
  NEXT_PUBLIC_ENABLE_LOGS = 'true'
  STUDIO_PG_META_URL = 'http://supabase-meta-bec.internal:8080'
  SUPABASE_URL = 'http://supabase-kong-bec.internal:8000'
  HOSTNAME = "::"
  HOST = "::"

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []

  [services.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 250

  [[services.http_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/platform/profile'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
