app = "supabase-studio"
primary_region = "lhr"

[build]
  image = "public.ecr.aws/supabase/studio:2025.07.07-sha-1d3b0ba"

[env]
  STUDIO_PG_META_URL = "http://supabase-meta.internal:8080"
  SUPABASE_URL = "http://supabase-kong.internal:8000"
  NEXT_PUBLIC_ENABLE_LOGS = "true"
  NEXT_ANALYTICS_BACKEND_PROVIDER = "postgres"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 250

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/api/platform/profile"
    protocol = "http"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024