# fly.toml app configuration file generated for supabase-studio-bec on 2025-07-22T14:49:20+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supabase-studio-bec'
primary_region = 'lhr'

[build]
  image = 'public.ecr.aws/supabase/studio:2025.07.07-sha-1d3b0ba'

[env]
  NEXT_ANALYTICS_BACKEND_PROVIDER = 'postgres'
  NEXT_PUBLIC_ENABLE_LOGS = 'true'
  STUDIO_PG_META_URL = 'http://supabase-meta-bec.flycast:8080'
  SUPABASE_URL = 'https://supabase-kong-bec.fly.dev'
  HOSTNAME = "::"
  HOST = "::"

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  # NOTE: not exposed to public because we don't have a public ip on this app
  # expose this so we can connect privately via flycast. we use flycast so
  # that fly will auto start the app when it's asleep.  
  [services.ports]
    port = 3000

  [services.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 250

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
