# fly.toml app configuration file generated for supabase-meta-bec on 2025-07-22T14:40:08+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supabase-meta-bec'
primary_region = 'lhr'

[build]
  image = 'public.ecr.aws/supabase/postgres-meta:v0.91.0'

[env]
  PG_META_PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  # NOTE: not exposed to public because we don't have a public ip on this app
  # expose this so we can connect privately via flycast. we use flycast so
  # that fly will auto start the app when it's asleep.  
  [services.ports]
    port = 8080

  [services.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 250

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
