# fly.toml app configuration file generated for supabase-meta-bec on 2025-07-22T14:40:08+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'supabase-meta-bec'
primary_region = 'lhr'

[build]
  image = 'public.ecr.aws/supabase/postgres-meta:v0.91.0'

[env]
  PG_META_PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []

  [services.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 250

  [[services.http_checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
