app = "supabase-meta"
primary_region = "lhr"

[build]
  image = "public.ecr.aws/supabase/postgres-meta:v0.91.0"

[env]
  PG_META_PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 250

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512